version: "3"

services:
  api-mongo:
    image: mongo:5.0.6
    container_name: mongo_to00bs65_3001_4
    restart: always
    networks:
      - private
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  api-server:
    build:
      args:
          - NODE_ENV=development
      context: backend
    command: yarn run dev-server
    container_name: api_to00bs65_3001_4
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=30014
      - MONGO_URL=mongodb://host.docker.internal:27017/api
    volumes:
      - /usr/app/node_modules
      - ./backend/logs:/logs
      - ./backend/src:/usr/app/src
      - ./backend/package.json:/usr/app/package.json
      - ./backend/package-lock.json:/usr/app/package-lock.json
    networks:
      - private
      - public
    ports:
      - 30014:30014
  frontend:
    build:
      context: frontend
      target: development
    container_name: frontend_to00bs65_3001_4
    ports:
      - 9000:9000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules/
    networks:
      - public
    depends_on:
      - api-server


volumes:
  db-data:

networks:
  private:
  public:
